# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 14:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='消息标题')),
                ('message', models.CharField(max_length=500, verbose_name='消息内容')),
                ('exploEviId', models.IntegerField(blank=True, null=True, verbose_name='所涉及的炸药物证')),
                ('devEviId', models.IntegerField(blank=True, null=True, verbose_name='所涉及的爆炸装置物证')),
                ('hasRead', models.BooleanField(default=False, verbose_name='是否已读')),
                ('hasHandle', models.BooleanField(default=False, verbose_name='是否处理')),
                ('sendDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
                ('receiveUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiveUser', to=settings.AUTH_USER_MODEL, verbose_name='收件人')),
                ('sendUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendUser', to=settings.AUTH_USER_MODEL, verbose_name='发件人')),
            ],
            options={
                'verbose_name': '站内消息信息表',
                'verbose_name_plural': '站内消息信息表',
            },
        ),
        migrations.CreateModel(
            name='userMessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtURL', models.FileField(blank=True, max_length=300, null=True, upload_to='file/userMessageFile/', verbose_name='站内消息文件路径')),
                ('userMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMessageFile', to='user_operation.userMessage', verbose_name='对应的站内消息信息')),
            ],
            options={
                'verbose_name': '站内消息文件表',
                'verbose_name_plural': '站内消息文件表',
            },
        ),
    ]
