# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 14:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allowUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exploEviId', models.IntegerField(blank=True, null=True, verbose_name='所涉及的炸药物证')),
                ('devEviId', models.IntegerField(blank=True, null=True, verbose_name='所涉及的炸药物证')),
                ('authorized', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized', to=settings.AUTH_USER_MODEL, verbose_name='授权的管理员')),
                ('entitled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitled', to=settings.AUTH_USER_MODEL, verbose_name='被授权的普通用户')),
            ],
            options={
                'verbose_name': '普通用户修改物证权限表',
                'verbose_name_plural': '普通用户修改物证权限表',
            },
        ),
        migrations.CreateModel(
            name='userMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='消息标题')),
                ('message', models.CharField(max_length=500, verbose_name='消息内容')),
                ('exploEviId', models.IntegerField(blank=True, null=True, verbose_name='所涉及的炸药物证')),
                ('devEviId', models.IntegerField(blank=True, null=True, verbose_name='所涉及的炸药物证')),
                ('hasRead', models.BooleanField(default=False, verbose_name='是否已读')),
                ('sendDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
                ('receiveUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiveUser', to=settings.AUTH_USER_MODEL, verbose_name='收件人')),
                ('sendUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendUser', to=settings.AUTH_USER_MODEL, verbose_name='发件人')),
            ],
            options={
                'verbose_name': '站内消息信息表',
                'verbose_name_plural': '站内消息信息表',
            },
        ),
    ]
