# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='hasHandle',
            field=models.BooleanField(default=False, verbose_name='是否处理'),
        ),
    ]
