# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explomatchgcms',
            name='msName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='匹配的MS文件名称'),
        ),
    ]
