# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devcompmatch',
            name='checkHandle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devCompMatchcheckHandle', to=settings.AUTH_USER_MODEL, verbose_name='普通核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='devcompmatch',
            name='expertHandle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devCompMatchexpertHandle', to=settings.AUTH_USER_MODEL, verbose_name='专家核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='devshapematch',
            name='checkHandle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devShapeMatchcheckHandle', to=settings.AUTH_USER_MODEL, verbose_name='普通核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='devshapematch',
            name='expertHandle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devShapeMatchexpertHandle', to=settings.AUTH_USER_MODEL, verbose_name='专家核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='devsynmatch',
            name='checkHandleComp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devSynMatchcheckHandleComp', to=settings.AUTH_USER_MODEL, verbose_name='成分普通核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='devsynmatch',
            name='checkHandleShape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devSynMatchcheckHandleShape', to=settings.AUTH_USER_MODEL, verbose_name='图像普通核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='devsynmatch',
            name='expertHandleComp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devSynMatchexpertHandleComp', to=settings.AUTH_USER_MODEL, verbose_name='成分专家核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='devsynmatch',
            name='expertHandleShape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devSynMatchexpertHandleShape', to=settings.AUTH_USER_MODEL, verbose_name='图像专家核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='logoimgmatch',
            name='checkHandle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logoImgMatchcheckHandle', to=settings.AUTH_USER_MODEL, verbose_name='普通核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='logoimgmatch',
            name='expertHandle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logoImgMatchexpertHandle', to=settings.AUTH_USER_MODEL, verbose_name='专家核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='opartimgmatch',
            name='checkHandle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oPartImgMatchcheckHandle', to=settings.AUTH_USER_MODEL, verbose_name='普通核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='opartimgmatch',
            name='expertHandle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oPartImgMatchexpertHandle', to=settings.AUTH_USER_MODEL, verbose_name='专家核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='pcbimgmatch',
            name='checkHandle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PCBImgMatchcheckHandle', to=settings.AUTH_USER_MODEL, verbose_name='普通核准人员（外键）'),
        ),
        migrations.AlterField(
            model_name='pcbimgmatch',
            name='expertHandle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PCBImgMatchexpertHandle', to=settings.AUTH_USER_MODEL, verbose_name='专家核准人员（外键）'),
        ),
    ]
