# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devshapematch',
            options={'ordering': ['-matchDegree'], 'verbose_name': '爆炸装置案件物证形态匹配结果表', 'verbose_name_plural': '爆炸装置案件物证形态匹配结果表'},
        ),
        migrations.AddField(
            model_name='devshapematch',
            name='matchPicURL',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='image/devShapeSample/match/', verbose_name='匹配的图片路径'),
        ),
    ]
