# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explosampleftirtestfile',
            name='txtHandledURL',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='处理过的TXT文档路径'),
        ),
    ]
