# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20181223_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devpartramantestfile',
            name='txtHandledURL',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='处理过的TXT文档路径'),
        ),
        migrations.AlterField(
            model_name='devpartsampleftirtestfile',
            name='txtHandledURL',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='处理过的TXT文档路径'),
        ),
        migrations.AlterField(
            model_name='devpartsamplexrftestfile',
            name='handledURL',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='有效元素列表'),
        ),
        migrations.AlterField(
            model_name='explosamplegcmsfile',
            name='txtHandledURL',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='处理过的TXT文档路径'),
        ),
        migrations.AlterField(
            model_name='explosampleramantestfile',
            name='txtHandledURL',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='处理过的TXT文档路径'),
        ),
        migrations.AlterField(
            model_name='explosamplexrdtestfile',
            name='txtHandledURL',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='处理过的TXT文档路径'),
        ),
        migrations.AlterField(
            model_name='explosamplexrftestfile',
            name='handledURL',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='有效元素列表'),
        ),
    ]
