# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20190304_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devshapesample',
            name='rectCoordi',
        ),
        migrations.AlterField(
            model_name='devshapesample',
            name='featureUrl',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='file/devShapeSample/feature', verbose_name='特征文件路径'),
        ),
        migrations.AlterField(
            model_name='devshapesample',
            name='maskURL',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='image/devShapeSample/mask/', verbose_name='PCB区域标记图像文件路径 '),
        ),
    ]
