# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20190305_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='devshapesample',
            name='rectCoordi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='矩形框坐标（4个）'),
        ),
    ]
