# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20190305_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=20, verbose_name='人员姓名'),
        ),
    ]
