# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devshapeevi',
            name='backCoordi',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='blackWhiteUrl',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='boardCheckCoordi',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='boardCoordi',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='compCheckCoordi',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='interColorUrl',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='isCircuit',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='isFirst',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='middleResultUrl',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='nomResolution',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='nomUrl',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='originalResolution',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='originalUrl',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='proCoordi',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='rectCoordi',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='resultFileUrl',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='resultPicUrl',
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='maskURL',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='', verbose_name='PCB区域标记图像文件路径 '),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='nResolution',
            field=models.IntegerField(blank=True, null=True, verbose_name='归一化图像分辨率'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='norImgURL',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='image/devShapeEvi/correction/', verbose_name='归一化图像文件路径'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='sResolution',
            field=models.IntegerField(blank=True, null=True, verbose_name='原始图像采集分辨率'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='srcImgURL',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='image/devShapeEvi/original/', verbose_name='原始图像文件路径'),
        ),
        migrations.AlterField(
            model_name='devshapeevi',
            name='featureUrl',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='', verbose_name='特征文件路径'),
        ),
        migrations.AlterField(
            model_name='devshapeevi',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
    ]
