# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evi', '0002_auto_20181223_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deveviftirtestfile',
            name='txtURL',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='file/devEviFTIRTestFile/', verbose_name='录入TXT文档路径'),
        ),
    ]
