# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evi', '0004_devshapeevi_rectcoordi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devshapeevi',
            name='nResolution',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='sResolution',
        ),
    ]
